-- CreateEnum
CREATE TYPE "Categories" AS ENUM ('LIFESTYLE_WELLNESS', 'TECHNOLOGY_INNOVATION', 'SOFTWARE_ENGINEERING_DEVELOPMENT', 'BUSINESS_FINANCE', 'ARTS_ENTERTAINMENT', 'NEWS_SOCIETY', 'SCIENCE_NATURE', 'POLITICS_GOVERNMENT', 'SPORTS_RECREATION', 'EDUCATION_CAREER', 'HEALTH_MEDICINE');

-- AlterTable
ALTER TABLE "Article" ADD COLUMN     "category" "Categories",
ADD COLUMN     "keywords" TEXT[];

-- CreateIndex
CREATE INDEX "Article_category_id_idx" ON "Article"("category" DESC, "id" DESC);
